### ISSUE TITLE
Error: "Your specified OSM file does not exist" happen in using hdfs

### ISSUE THREAD

**Issue by gusugusu1018** [zishanfu/GeoSparkSim#3]
Hi @zishanfu, 

I want to run geosparksim stable branch using hdfs.
but an error has occurred like bellow.

The demonstration video seems to use hdfs in the output folder, how do you do it?

please, help me.

```
2020-07-01 14:50:23 INFO  MyGraphHopper:646 - version 0.8.2|2016-10-19T17:38:28Z (5,14,4,3,3,2)
2020-07-01 14:50:23 INFO  MyGraphHopper:648 - graph car|RAM_STORE|2D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308
2020-07-01 14:50:23 INFO  MyGraphHopper:725 - start creating graph from hdfs://gusugusu-hadoop-master:8020/user/hadoop/geosparksim/geosparksim/map.osm
2020-07-01 14:50:23 INFO  MyGraphHopper:711 - using car|RAM_STORE|2D|NoExt|,,,,, memory:totalMB:344, usedMB:165
Exception in thread "Thread-31" java.lang.IllegalStateException: Your specified OSM file does not exist:/home/hadoop/GeoSparkSim_ws/geosparksim_stable/hdfs:/gusugusu-hadoop-master:8020/user/hadoop/geosparksim/geosparksim/map.osm
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:143)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:712)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:681)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:659)
	at com.zishanfu.geosparksim.shortestpath.Graph.<init>(Graph.java:29)
	at com.zishanfu.geosparksim.generation.CreateVehicles.<init>(CreateVehicles.java:24)
	at com.zishanfu.geosparksim.interaction.handler.GenerateBtnHandler.lambda$actionPerformed$0(GenerateBtnHandler.java:158)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zishanfu** [comment]
I think the problem is your HDFS path was wrong. You might need to double-check it.
